import { Link } from "react-router-dom";
import StaticPageShell from "./StaticPageShell";

const faqs: { q: string; a: string }[] = [
  {
    q: "Is Leap.ai really free?",
    a: "Yes. The free plan is free forever — no card, no trial countdown. It includes your personalized roadmap, recommended practice problems with a real code judge, trial real-world scenarios, and community access. Paid plans exist for people who want the full practice library, interview & exam prep, and creator content — free isn't a bait.",
  },
  {
    q: "Why pay when roadmaps are free on roadmap.sh or from AI agents?",
    a: "Because the roadmap itself is free here. You pay for what a static roadmap can't do: a practice engine with a real code judge, real-world case studies and build projects, interview & exam prep tracks, an AI assistant that knows your profile and progress, and live workshops and courses from creators. Free users get a real taste of each; Pro unlocks the full library.",
  },
  {
    q: "How much do paid plans cost?",
    a: "Career Audit is a one-time $12 (also ₦15,000) — a full profile + resume review with a prioritized skill-gap analysis and action plan. Pro is $12/month (also ₦15,000) or $100/year (≈ 30% off) for the full practice library, real-world scenarios, unlimited roadmaps, goal tracking, AI insights, and creator tools. Prices show in your currency at checkout.",
  },
  {
    q: "How does the roadmap generator work?",
    a: "You tell us your current role, target role, and timeline. We analyze the gap and generate a step-by-step plan — skills to build, projects to ship, milestones to hit, in order. Roadmaps are generated by a real language model and take about 30 seconds. If the free AI model is rate-limited, it falls back to our built-in generator so you always get a plan.",
  },
  {
    q: "Is my career profile private?",
    a: "Your profile drives your roadmap and isn't shown publicly. We don't sell data or show ads. For the full picture — including the third-party providers that process your data — see the Privacy Policy.",
  },
  {
    q: "How do payments work?",
    a: "Checkout is live and handled by Paystack in NGN, USD, GHS, ZAR, or KES. Card details never touch our servers. Subscriptions renew monthly/yearly until you cancel; the one-time Career Audit is a single charge.",
  },
  {
    q: "What is the practice problem set?",
    a: "A real coding-practice environment: problems with hidden test cases, a compile-and-run judge with time and memory limits, and pass/fail results. You write Java in the browser and submit to see exactly which cases pass. It's built in-house — no external judge service.",
  },
  {
    q: "What does 'early access' mean?",
    a: "It means the product is young and changing fast, and we'd rather tell you that than pretend otherwise. Things may break, and your feedback genuinely decides what ships next. That honesty is a feature.",
  },
];

const FAQ = () => (
  <StaticPageShell>
    <div className="mx-auto max-w-3xl px-5 py-16 sm:px-8 sm:py-20">
      <p className="font-mono text-[11px] uppercase tracking-[0.2em] text-[#C2410C]">
        FAQ
      </p>
      <h1 className="mt-3 font-display text-4xl font-medium tracking-tight sm:text-5xl">
        Frequently asked questions
      </h1>
      <p className="mt-4 max-w-xl text-[15px] leading-relaxed text-stone-600">
        Straight answers, no sales-speak. If your question isn't here, ask a human.
      </p>

      <div className="mt-10 space-y-8">
        {faqs.map((f) => (
          <section key={f.q} className="border-t border-stone-200 pt-6">
            <h2 className="text-[15px] font-semibold tracking-tight">{f.q}</h2>
            <p className="mt-2 text-[14px] leading-relaxed text-stone-600">{f.a}</p>
          </section>
        ))}
      </div>

      <div className="mt-12 border border-stone-900 bg-white p-6">
        <h2 className="text-[15px] font-semibold tracking-tight">Still have a question?</h2>
        <p className="mt-2 text-[14px] leading-relaxed text-stone-600">
          Send it through the contact form — a human reads every message.
        </p>
        <Link
          to="/contact"
          className="mt-4 inline-block bg-stone-900 px-4 py-2 text-[13px] text-white hover:bg-stone-700"
        >
          Ask a human
        </Link>
      </div>
    </div>
  </StaticPageShell>
);

export default FAQ;
