import React, { useEffect, useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { BookOpen, ExternalLink, Loader2, RefreshCw } from "lucide-react";
import { apiGet, apiPost } from "@/lib/api";
import { useAI } from "@/context/AIContext";
import { Link } from "react-router-dom";

interface RoadmapPhase {
  title: string;
  duration?: string;
  focus?: string;
  skills?: string[];
  milestones?: string[];
  resources?: { title: string; type?: string }[];
  references?: { label: string; url: string }[];
}

interface RoadmapResponse {
  source?: string;
  roadmap?: {
    summary?: string;
    phases?: RoadmapPhase[];
  };
}

interface RoadmapTabProps {
  refreshKey?: number;
}

export const RoadmapTab: React.FC<RoadmapTabProps> = ({ refreshKey = 0 }) => {
  const { profile } = useAI();
  const [roadmap, setRoadmap] = useState<RoadmapResponse["roadmap"] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const loadRoadmap = () => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    // Load the saved roadmap first (instant, no LLM cost) — only generate a
    // fresh one when the user has none. This makes the dashboard fast instead
    // of burning an LLM call on every visit.
    const tryLoad = () => {
      apiGet<{ roadmap?: RoadmapResponse["roadmap"] }>("/insights/roadmap")
        .then((res) => {
          if (!cancelled) {
            if (res.roadmap?.phases?.length) {
              setRoadmap(res.roadmap);
              setLoading(false);
            } else {
              generate();
            }
          }
        })
        .catch(() => {
          if (!cancelled) generate();
        });
    };
    const generate = () => {
      if (cancelled) return;
      // Build the request from the user's real profile (saved during onboarding).
      // The backend merges whatever's missing with the user's saved profile, so
      // an empty profile still yields a real roadmap — just not one personalized
      // to role names the user never entered.
      const request = {
        currentRole: profile?.currentRole || undefined,
        targetRole: profile?.targetRole || undefined,
        timeframe: profile?.timeframe || undefined,
        industry: profile?.industry || undefined,
        yearsExperience: profile?.yearsExperience || undefined,
        focusAreas: profile?.interests?.length ? profile.interests.slice(0, 3) : undefined,
      };
      apiPost<RoadmapResponse>("/insights/roadmap", request)
        .then((res) => {
          if (!cancelled) {
            if (res.roadmap?.phases?.length) {
              setRoadmap(res.roadmap);
            } else {
              setError("The roadmap came back empty. Please try again.");
            }
          }
        })
        .catch(() => {
          if (!cancelled) setError("Could not reach the server. It may be waking up — please retry.");
        })
        .finally(() => {
          if (!cancelled) setLoading(false);
        });
    };
    tryLoad();
    return () => {
      cancelled = true;
    };
  };

  useEffect(() => {
    return loadRoadmap();
  }, [profile, refreshKey]);

  if (loading) {
    return (
      <Card>
        <CardContent className="flex items-center justify-center py-16 text-muted-foreground">
          <Loader2 className="mr-2 h-5 w-5 animate-spin" />
          Generating your personalized roadmap…
        </CardContent>
      </Card>
    );
  }

  if (error) {
    return (
      <Card>
        <CardContent className="py-16 text-center">
          <p className="text-sm text-muted-foreground mb-4">{error}</p>
          <Button variant="outline" size="sm" onClick={loadRoadmap}>
            <RefreshCw className="mr-2 h-3 w-3" />
            Try again
          </Button>
        </CardContent>
      </Card>
    );
  }

  if (roadmap?.phases?.length) {
    return (
      <Card>
        <CardHeader className="pb-2">
          <div className="flex flex-wrap justify-between items-center gap-3">
            <div>
              <CardTitle>{roadmap.summary ? "Your Personalized Roadmap" : "Career Roadmap"}</CardTitle>
              {roadmap.summary && <CardDescription>{roadmap.summary}</CardDescription>}
              {roadmap.source && (
                <CardDescription className="text-xs">
                  Generated by the {roadmap.source === "llm" ? "AI model" : "Leap.ai engine"}
                </CardDescription>
              )}
            </div>
            <Link to="/onboarding">
              <Button variant="outline" size="sm">
                Update my profile
              </Button>
            </Link>
          </div>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {roadmap.phases.map((phase, i) => (
              <div key={phase.title + i} className="p-4 border rounded-lg">
                <div className="flex items-start">
                  <div className="bg-leap-purple/10 p-2 rounded-full text-leap-purple mr-3">
                    <BookOpen size={20} />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center justify-between flex-wrap gap-2">
                      <h3 className="font-medium">{phase.title}</h3>
                      {phase.duration && (
                        <span className="text-xs font-medium text-muted-foreground">{phase.duration}</span>
                      )}
                    </div>
                    {phase.focus && (
                      <p className="text-sm text-muted-foreground mb-2">{phase.focus}</p>
                    )}
                    {phase.skills?.length ? (
                      <div className="flex flex-wrap gap-1.5 mb-2">
                        {phase.skills.map((skill) => (
                          <span key={skill} className="text-xs px-2 py-0.5 rounded-full bg-muted">
                            {skill}
                          </span>
                        ))}
                      </div>
                    ) : null}
                    {phase.milestones?.length ? (
                      <ul className="text-sm space-y-1 mb-2">
                        {phase.milestones.map((milestone) => (
                          <li key={milestone} className="flex items-start gap-2">
                            <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-leap-purple shrink-0" />
                            {milestone}
                          </li>
                        ))}
                      </ul>
                    ) : null}
                    {phase.resources?.length ? (
                      <p className="text-xs text-muted-foreground">
                        Resources: {phase.resources.map((r) => r.title).join(" · ")}
                      </p>
                    ) : null}
                    {phase.references?.length ? (
                      <div className="flex flex-wrap gap-x-4 gap-y-1 mt-1">
                        {phase.references.map((ref) => (
                          <a
                            key={ref.url}
                            href={ref.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-center text-xs text-leap-purple hover:underline"
                          >
                            {ref.label} <ExternalLink size={12} className="ml-1" />
                          </a>
                        ))}
                      </div>
                    ) : null}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    );
  }

  // Honest empty state — the API succeeded but returned nothing usable.
  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle>Career Roadmap</CardTitle>
        <CardDescription>Your personalized career path</CardDescription>
      </CardHeader>
      <CardContent>
        <p className="text-sm text-muted-foreground mb-4">
          We couldn't build a roadmap yet. Make sure your profile has a target role, then try again.
        </p>
        <div className="flex gap-3">
          <Link to="/onboarding">
            <Button size="sm">Update my profile</Button>
          </Link>
          <Button variant="outline" size="sm" onClick={loadRoadmap}>
            <RefreshCw className="mr-2 h-3 w-3" />
            Try again
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};
