package com.leapai.backend.controller;

import com.leapai.backend.config.UserContext;
import com.leapai.backend.service.CustomPracticeService;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Map;

/**
 * The real, personalized practice engine — every exercise is generated by
 * the LLM from the user's actual profile (see CustomPracticeService), not
 * picked from a fixed catalog and not assumed to be a coding problem.
 */
@RestController
@RequestMapping("/api/practice/custom")
public class CustomPracticeController {

    private final CustomPracticeService service;

    public CustomPracticeController(CustomPracticeService service) {
        this.service = service;
    }

    @PostMapping("/generate")
    public Map<String, Object> generate() {
        return service.generate(UserContext.require());
    }

    @GetMapping
    public Map<String, Object> list() {
        return Map.of("items", service.list(UserContext.require()));
    }

    @PostMapping("/{itemId}/submit")
    public Map<String, Object> submit(@PathVariable Long itemId, @RequestBody Map<String, Object> body) {
        String response = body.get("response") == null ? "" : String.valueOf(body.get("response"));
        return service.submit(itemId, UserContext.require(), response);
    }
}
